const RowFields = {
    COUNTERPARTY : 'Counterparty',
    NAME : 'Name',
    RECEIVEINDEX : 'ReceiveIndex',
    UNDERLIER : 'Underlier',
    RHO10BPS : 'Rho10bps',
    GAMMA1PCT : 'Gamma1pct',
    DELTA1PCT : 'Delta1pct',
    VEGA1PCT : 'Vega1pt',
    LASTUPDATED : 'LastUpdated',
    RECEIVELEG : 'ReceiveLeg',
    VERTEX : 'Vertex',
    PRICE : 'Price',
    PAYLEG : 'PayLeg',
    VOLATILITY : 'Volatility',
    PAYCURRENCY : 'PayCurrency',
    PAYDISCOUNTCURVE : 'PayDiscountCurve',
    PAYFIXEDRATE : 'PayFixedRate',
    MATURITYDATE : 'MaturityDate',
    PAYNOTIONAL : 'PayNotional',
    RECEIVEDISCOUNTCURVE : 'ReceiveDiscountCurve',
    RECEIVENOTIONAL : 'ReceiveNotional',
    RECEIVECURRENCY : 'ReceiveCurrency',
    RECEIVESPREAD : 'ReceiveSpread',
    AMEROREURO : 'AmerOrEuro',
    PUTORCALL : 'PutOrCall',
    CONTRACTSIZE : 'ContractSize',
    STRIKE : 'Strike'
}

export default RowFields;